// <auto-generated />
using System;
using Gorkem_.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gorkem_.Migrations
{
    [DbContext(typeof(GorkemDbContext))]
    [Migration("20241213082558_IdareciAdayIdareci")]
    partial class IdareciAdayIdareci
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_Askerlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_Askerliks");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_Birim", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("AktifYazismaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirimBransAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("BirimBransID")
                        .HasColumnType("tinyint");

                    b.Property<string>("BirimTuruAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("BirimTuruID")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("BuyukSehirmi")
                        .HasColumnType("bit");

                    b.Property<string>("EGMBirimTuruAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("EGMBirimTuruID")
                        .HasColumnType("tinyint");

                    b.Property<string>("IlAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IlID")
                        .HasColumnType("bigint");

                    b.Property<byte?>("IlPlakaNo")
                        .HasColumnType("tinyint");

                    b.Property<string>("IlUzunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IlceAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IlceID")
                        .HasColumnType("bigint");

                    b.Property<string>("IlceUzunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KadroAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("KadroID")
                        .HasColumnType("bigint");

                    b.Property<string>("KadroUzunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubeAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SubeID")
                        .HasColumnType("bigint");

                    b.Property<string>("SubeUzunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TabloID")
                        .HasColumnType("bigint");

                    b.Property<string>("UstBirimAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UstBirimID")
                        .HasColumnType("bigint");

                    b.Property<string>("UstBirimUzunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UzunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YazismaKodu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KT_Birims");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_Brans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_Branss");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_Cins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_Cinss");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_GorevYeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_GorevYeris");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_IdareciDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_IdareciDurum");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_Irk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_Irks");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_KadroIl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_KadroIls");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_Karar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Neticesi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_Karars");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_KopekDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_KopekDurumus");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_KursDegerlendirmeSorular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("DegerlendirmeTuru")
                        .HasColumnType("int");

                    b.Property<int>("MaxPuan")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_KursDegerlendirmeSorular");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_KursEgitimListesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_KursEgitimListesis");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_KursMufredat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("KursEgitimListesiId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KursEgitimListesiId");

                    b.ToTable("KT_KursMufredats");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_OgrenimDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UT_AdayIdareciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UT_AdayIdareciId");

                    b.ToTable("KT_OgrenimDurumus");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_Rutbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_Rutbes");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_SecimTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("KT_SecimTests");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_Soru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<int>("SecimTestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SecimTestId");

                    b.ToTable("KT_Sorus");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_YabanciDil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UT_AdayIdareciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UT_AdayIdareciId");

                    b.ToTable("KT_YabanciDils");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_AdayIdareci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("AskerlikId")
                        .HasColumnType("int");

                    b.Property<int>("BransId")
                        .HasColumnType("int");

                    b.Property<string>("CepTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("IdareciDurumId")
                        .HasColumnType("int");

                    b.Property<int>("KadroIlId")
                        .HasColumnType("int");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<int>("RutbeId")
                        .HasColumnType("int");

                    b.Property<int>("Sicil")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TestTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestiYapanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AskerlikId");

                    b.HasIndex("BransId");

                    b.HasIndex("IdareciDurumId");

                    b.HasIndex("KadroIlId");

                    b.HasIndex("RutbeId");

                    b.HasIndex("TestiYapanId");

                    b.ToTable("UT_Idarecis");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_HaftalıkDegerlendirmeRaporuGozlemler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Gozlemler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hafta")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<int>("KursiyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("KursiyerId");

                    b.ToTable("UT_HaftalıkDegerlendirmeRaporuGozlemlers");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Idareci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("IdareciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdareciId");

                    b.ToTable("UT_Idareci");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_IdareciKopekleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("IdareciId")
                        .HasColumnType("int");

                    b.Property<int>("KopekId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdareciId");

                    b.HasIndex("KopekId");

                    b.ToTable("UT_IdareciKopekleri");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Komisyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("GorevYeriId")
                        .HasColumnType("int");

                    b.Property<string>("KomisyonAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevYeriId");

                    b.ToTable("UT_Komisyons");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KomisyonUyeleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("CepTelefonu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GorevUnvani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevYeriId")
                        .HasColumnType("int");

                    b.Property<int?>("Sicil")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.Property<string>("TcKimlikNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GorevYeriId");

                    b.ToTable("UT_KomisyonUyeleris");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Kopek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int?>("AnneKopekId")
                        .HasColumnType("int");

                    b.Property<int?>("BabaKopekId")
                        .HasColumnType("int");

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<int>("BransId")
                        .HasColumnType("int");

                    b.Property<int>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<string>("CipNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EdinilenKisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdinilenKisiAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EdinilenKisiTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EdinilmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("EdinimSekli")
                        .HasColumnType("int");

                    b.Property<int>("IrkId")
                        .HasColumnType("int");

                    b.Property<int>("KadroIlId")
                        .HasColumnType("int");

                    b.Property<int>("KararId")
                        .HasColumnType("int");

                    b.Property<string>("KopekAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KopekDurum")
                        .HasColumnType("int");

                    b.Property<string>("KuvveNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NihaiKanaat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.Property<string>("YapilanIslem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnneKopekId");

                    b.HasIndex("BabaKopekId");

                    b.HasIndex("BirimId");

                    b.HasIndex("BransId");

                    b.HasIndex("IrkId");

                    b.HasIndex("KadroIlId");

                    b.HasIndex("KararId");

                    b.ToTable("UT_Kopek_Kopeks");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KopekCalKad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("AtamaEvrakSayısı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AtamaTuru")
                        .HasColumnType("int");

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<int?>("IdareciId")
                        .HasColumnType("int");

                    b.Property<int?>("KopekId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_EvrakAtama")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_GoreveBaslama")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_IlisikKesme")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("IdareciId");

                    b.HasIndex("KopekId");

                    b.ToTable("UT_KopekCalKads");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KopekDurumHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("KopekDurum")
                        .HasColumnType("int");

                    b.Property<int>("KopekId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KopekId");

                    b.ToTable("UT_KopekDurumHistory");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KopekVeIdareciDegerlendirmeFormu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int?>("AracToplamPuan")
                        .HasColumnType("int");

                    b.Property<int?>("KapaliAlanToplamPuan")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TasinabilirEsyaToplamPuan")
                        .HasColumnType("int");

                    b.Property<int>("TestinYapildigiIlId")
                        .HasColumnType("int");

                    b.Property<string>("TestinYapildigiYer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("TestinYapildigiIlId");

                    b.ToTable("UT_KopekVeIdareciDegerlendirmeFormu");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("Donem")
                        .HasColumnType("int");

                    b.Property<int?>("KursEgitimListesiId")
                        .HasColumnType("int");

                    b.Property<int?>("KursYeriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_KursBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_KursBitis")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KursEgitimListesiId");

                    b.HasIndex("KursYeriId");

                    b.ToTable("UT_Kurs");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KursDegerlendirmeCevap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("AracPuan")
                        .HasColumnType("int");

                    b.Property<int>("DegerlendirmeSoruId")
                        .HasColumnType("int");

                    b.Property<int>("DegerlendirmeTuru")
                        .HasColumnType("int");

                    b.Property<int>("KapaliAlanPuan")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<int>("KursiyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.Property<int>("TasinabilirEsyaPuan")
                        .HasColumnType("int");

                    b.Property<int?>("UT_KopekVeIdareciDegerlendirmeFormuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DegerlendirmeSoruId");

                    b.HasIndex("KursiyerId");

                    b.HasIndex("UT_KopekVeIdareciDegerlendirmeFormuId");

                    b.ToTable("UT_KursDegerlendirmeCevap");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KursEgitmenler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int?>("BirimId")
                        .HasColumnType("int");

                    b.Property<int?>("RutbeId")
                        .HasColumnType("int");

                    b.Property<int>("Sicil")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("RutbeId");

                    b.ToTable("UT_KursEgitmenler");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KursGunlukRapor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<string>("SinifAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("T_DersTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.ToTable("UT_KursGunlukRapors");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KursGunlukRaporDersler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("KursGunlukRaporId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("KursGunlukRaporId");

                    b.ToTable("UT_KursGunlukRaporDersler");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Kursiyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("CipNumarası")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KopekId")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<string>("PersonelAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sicil")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KopekId");

                    b.HasIndex("KursId");

                    b.ToTable("UT_Kursiyer");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_SecimTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<string>("Degerlendirme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Havlama")
                        .HasColumnType("bit");

                    b.Property<int?>("KomisyonId")
                        .HasColumnType("int");

                    b.Property<int>("KopekId")
                        .HasColumnType("int");

                    b.Property<int>("SecimTestBrans")
                        .HasColumnType("int");

                    b.Property<int>("SecimTestId")
                        .HasColumnType("int");

                    b.Property<int>("SinavYeriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TepkiSekli")
                        .HasColumnType("bit");

                    b.Property<int>("ToplamPuan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KomisyonId");

                    b.HasIndex("KopekId");

                    b.HasIndex("SecimTestId");

                    b.HasIndex("SinavYeriId");

                    b.ToTable("UT_SecimTests");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_SecimTestiCevap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktifmi")
                        .HasColumnType("bit");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<DateTime>("T_Aktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("T_Pasif")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtSecimTestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.HasIndex("UtSecimTestId");

                    b.ToTable("UT_SecimTestiCevaplar");
                });

            modelBuilder.Entity("UT_KomisyonUT_KomisyonUyeleri", b =>
                {
                    b.Property<int>("KomisyonId")
                        .HasColumnType("int");

                    b.Property<int>("KomisyonUyeleriId")
                        .HasColumnType("int");

                    b.HasKey("KomisyonId", "KomisyonUyeleriId");

                    b.HasIndex("KomisyonUyeleriId");

                    b.ToTable("UT_KomisyonUT_KomisyonUyeleri");
                });

            modelBuilder.Entity("UT_KursUT_KursEgitmenler", b =>
                {
                    b.Property<int>("KursEgitmenlerId")
                        .HasColumnType("int");

                    b.Property<int>("KurslarId")
                        .HasColumnType("int");

                    b.HasKey("KursEgitmenlerId", "KurslarId");

                    b.HasIndex("KurslarId");

                    b.ToTable("UT_KursUT_KursEgitmenler");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_KursMufredat", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_KursEgitimListesi", "KursEgitimListesi")
                        .WithMany()
                        .HasForeignKey("KursEgitimListesiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KursEgitimListesi");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_OgrenimDurumu", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_AdayIdareci", null)
                        .WithMany("OgrenimDurumu")
                        .HasForeignKey("UT_AdayIdareciId");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_Soru", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_SecimTest", "SecimTest")
                        .WithMany()
                        .HasForeignKey("SecimTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecimTest");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.KT_YabanciDil", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_AdayIdareci", null)
                        .WithMany("YabanciDil")
                        .HasForeignKey("UT_AdayIdareciId");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_AdayIdareci", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_Askerlik", "Askerlik")
                        .WithMany()
                        .HasForeignKey("AskerlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_Brans", "Brans")
                        .WithMany()
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_IdareciDurum", "IdareciDurum")
                        .WithMany()
                        .HasForeignKey("IdareciDurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_KadroIl", "KadroIl")
                        .WithMany()
                        .HasForeignKey("KadroIlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_Rutbe", "Rutbe")
                        .WithMany()
                        .HasForeignKey("RutbeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_KursEgitmenler", "TestiYapan")
                        .WithMany()
                        .HasForeignKey("TestiYapanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Askerlik");

                    b.Navigation("Brans");

                    b.Navigation("IdareciDurum");

                    b.Navigation("KadroIl");

                    b.Navigation("Rutbe");

                    b.Navigation("TestiYapan");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_HaftalıkDegerlendirmeRaporuGozlemler", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_Kursiyer", "Kursiyer")
                        .WithMany()
                        .HasForeignKey("KursiyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Kursiyer");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Idareci", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_AdayIdareci", "Idareci")
                        .WithMany()
                        .HasForeignKey("IdareciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idareci");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_IdareciKopekleri", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_Idareci", "Idareci")
                        .WithMany("Kopek")
                        .HasForeignKey("IdareciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_Kopek", "Kopek")
                        .WithMany("Idareci")
                        .HasForeignKey("KopekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idareci");

                    b.Navigation("Kopek");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Komisyon", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_GorevYeri", "GorevYeri")
                        .WithMany()
                        .HasForeignKey("GorevYeriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GorevYeri");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KomisyonUyeleri", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_GorevYeri", "GorevYeri")
                        .WithMany()
                        .HasForeignKey("GorevYeriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GorevYeri");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Kopek", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_Kopek", "AnneKopek")
                        .WithMany()
                        .HasForeignKey("AnneKopekId");

                    b.HasOne("Gorkem_.Context.Entities.UT_Kopek", "BabaKopek")
                        .WithMany()
                        .HasForeignKey("BabaKopekId");

                    b.HasOne("Gorkem_.Context.Entities.KT_Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId");

                    b.HasOne("Gorkem_.Context.Entities.KT_Brans", "Brans")
                        .WithMany()
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_Irk", "Irk")
                        .WithMany()
                        .HasForeignKey("IrkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_KadroIl", "KadroIl")
                        .WithMany()
                        .HasForeignKey("KadroIlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_Karar", "Karar")
                        .WithMany()
                        .HasForeignKey("KararId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnneKopek");

                    b.Navigation("BabaKopek");

                    b.Navigation("Birim");

                    b.Navigation("Brans");

                    b.Navigation("Irk");

                    b.Navigation("KadroIl");

                    b.Navigation("Karar");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KopekCalKad", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId");

                    b.HasOne("Gorkem_.Context.Entities.UT_Idareci", "Idareci")
                        .WithMany()
                        .HasForeignKey("IdareciId");

                    b.HasOne("Gorkem_.Context.Entities.UT_Kopek", "Kopek")
                        .WithMany()
                        .HasForeignKey("KopekId");

                    b.Navigation("Birim");

                    b.Navigation("Idareci");

                    b.Navigation("Kopek");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KopekDurumHistory", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_Kopek", "Kopek")
                        .WithMany()
                        .HasForeignKey("KopekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kopek");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KopekVeIdareciDegerlendirmeFormu", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_GorevYeri", "TestinYapildigiIl")
                        .WithMany()
                        .HasForeignKey("TestinYapildigiIlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("TestinYapildigiIl");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Kurs", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_KursEgitimListesi", "KursEgitimListesi")
                        .WithMany()
                        .HasForeignKey("KursEgitimListesiId");

                    b.HasOne("Gorkem_.Context.Entities.KT_GorevYeri", "KursYeri")
                        .WithMany()
                        .HasForeignKey("KursYeriId");

                    b.Navigation("KursEgitimListesi");

                    b.Navigation("KursYeri");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KursDegerlendirmeCevap", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_KursDegerlendirmeSorular", "DegerlendirmeSoru")
                        .WithMany()
                        .HasForeignKey("DegerlendirmeSoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_Kursiyer", "Kursiyer")
                        .WithMany()
                        .HasForeignKey("KursiyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_KopekVeIdareciDegerlendirmeFormu", null)
                        .WithMany("KursDegerlendirmeCevaplar")
                        .HasForeignKey("UT_KopekVeIdareciDegerlendirmeFormuId");

                    b.Navigation("DegerlendirmeSoru");

                    b.Navigation("Kursiyer");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KursEgitmenler", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId");

                    b.HasOne("Gorkem_.Context.Entities.KT_Rutbe", "Rutbe")
                        .WithMany()
                        .HasForeignKey("RutbeId");

                    b.Navigation("Birim");

                    b.Navigation("Rutbe");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KursGunlukRapor", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KursGunlukRaporDersler", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_KursMufredat", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_KursGunlukRapor", "KursGunlukRapor")
                        .WithMany("KursGunlukRaporDersler")
                        .HasForeignKey("KursGunlukRaporId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("KursGunlukRapor");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Kursiyer", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_Kopek", "Kopek")
                        .WithMany()
                        .HasForeignKey("KopekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_Kurs", "Kurs")
                        .WithMany("Kursiyerler")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kopek");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_SecimTest", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_Komisyon", "Komisyon")
                        .WithMany()
                        .HasForeignKey("KomisyonId");

                    b.HasOne("Gorkem_.Context.Entities.UT_Kopek", "Kopek")
                        .WithMany()
                        .HasForeignKey("KopekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_SecimTest", "SecimTest")
                        .WithMany()
                        .HasForeignKey("SecimTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.KT_GorevYeri", "SinavYeri")
                        .WithMany()
                        .HasForeignKey("SinavYeriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komisyon");

                    b.Navigation("Kopek");

                    b.Navigation("SecimTest");

                    b.Navigation("SinavYeri");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_SecimTestiCevap", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.KT_Soru", "Soru")
                        .WithMany()
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_SecimTest", "UtSecimTest")
                        .WithMany()
                        .HasForeignKey("UtSecimTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");

                    b.Navigation("UtSecimTest");
                });

            modelBuilder.Entity("UT_KomisyonUT_KomisyonUyeleri", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_Komisyon", null)
                        .WithMany()
                        .HasForeignKey("KomisyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_KomisyonUyeleri", null)
                        .WithMany()
                        .HasForeignKey("KomisyonUyeleriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UT_KursUT_KursEgitmenler", b =>
                {
                    b.HasOne("Gorkem_.Context.Entities.UT_KursEgitmenler", null)
                        .WithMany()
                        .HasForeignKey("KursEgitmenlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gorkem_.Context.Entities.UT_Kurs", null)
                        .WithMany()
                        .HasForeignKey("KurslarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_AdayIdareci", b =>
                {
                    b.Navigation("OgrenimDurumu");

                    b.Navigation("YabanciDil");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Idareci", b =>
                {
                    b.Navigation("Kopek");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Kopek", b =>
                {
                    b.Navigation("Idareci");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KopekVeIdareciDegerlendirmeFormu", b =>
                {
                    b.Navigation("KursDegerlendirmeCevaplar");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_Kurs", b =>
                {
                    b.Navigation("Kursiyerler");
                });

            modelBuilder.Entity("Gorkem_.Context.Entities.UT_KursGunlukRapor", b =>
                {
                    b.Navigation("KursGunlukRaporDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
