# Uygulamanın çalışacağı runtime imajı (ASP.NET Core runtime 8.0)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# SDK 8.0 imajını kullanarak uygulamanın derlenmesini sağlıyoruz
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Gorkem_.csproj", "./"]
RUN dotnet restore "Gorkem_.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "Gorkem_.csproj" -c Release -o /app/build

# Yayınlamak için derlenmiş projeyi kopyalıyoruz
FROM build AS publish
RUN dotnet publish "Gorkem_.csproj" -c Release -o /app/publish

# Yayınlanmış uygulamayı çalıştırmak için baz imajı kullanıyoruz
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Gorkem_.dll"]
